### ISSUE TITLE
Tabelle für inaktive Mitglieder (change request von Michi)

### ISSUE THREAD

**Issue by office-ultimate** [oefsv/ulti-players#54]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by flokain** [comment]
![image](https://user-images.githubusercontent.com/14279221/109276660-920ef700-7816-11eb-94ec-26b6e66dfcd9.png)
![image](https://user-images.githubusercontent.com/14279221/109276850-d39fa200-7816-11eb-8933-9962c30116a9.png)

**Comment by flokain** [comment]
@office-ultimate ist erledigt
