### ISSUE TITLE
Registrierung mit (vermutlich) abgelaufener Email gibt "Server Error (500)"

### ISSUE THREAD

**Issue by JakobMiksch** [oefsv/ulti-players#56]
Habe mich mit meiner Emailadresse (die freigeschalten sein sollte) versucht zu registrieren indem ich auf "Passwort vergessen" geklickt habe. Dann kam eine leere Seite mit "Server Error (500)" Ich vermute, dass meine Emailadresse abgelaufen ist, da die Passwortwiederherstellung mit anderen Emailadressen nicht abstürzt. 

Habe das Problem auch schon an office@***verband.at geschrieben ...

Danke auf alle Fälle für Eure Arbeit und cool dass ihr die Anwendung Open Source stellt :+1:  :+1:

**Comment by flokain** [comment]
danke für die Bugmeldung.
Das problem liegt vermutlich nicht an deiner email sondern an der server mail adresse. die applikation kann deshalb keine mail verschicken. ich melde mich sobald das problem behoben ist.
