### ISSUE TITLE
Filter "By nur ein Verein"

### ISSUE THREAD

**Issue by office-ultimate** [oefsv/ulti-players#57]
Hi Flo,

wenn ich nach Spieler*innen filtere, die bei mehr als einem Verein als Stammspieler*innen gemeldet sind, dann erhalte ich eine Liste mit 17 Spieler*innen. Dabei kommt es manchmal vor (z.B. bei Felix Reith), dass zwei Mal derselbe Verein eingetragen ist.

Alles Liebe
Corinna

**Comment by flokain** [comment]
Hi corrina,

Geundsätzlich ist das möglich da eine Mitgliedschaft immer über einen
gewissen zeitraum geht. Er kann zb 2016-2017 bei innsiders sein 2018-2019
bei uvie und dann ab 2020 wieder bei innsiders.

Warum er trotzdem in der Liste erscheint, ist weil beide Mitgliedschaften
kein Endatum haben dadurch sind beide unbefristet und aktiv und das darf
nicht sein.

In so einem fall muss mann die vereinsadmins fragen ob er zwischenzeitlich
ausgetreten war und die frühere Mitgliedschaft mit dem damaligen
Austrittsdatum versehen oder es war ein versehen und eine Mitgliedschaft
wird gelöscht.


LG
Flo

office-ultimate <notifications@github.com> schrieb am Mo., 21. Sep. 2020,
11:13:
